[package]
name = "rs-pq-inmem-cols2ints"
version = "0.1.0"
edition = "2024"

description = "Converts the column of the parquet to ints for wasi."
license = "Apache-2.0"
repository = "https://github.com/takanoriyanagitani/rs-pq-inmem-cols2ints"
homepage = "https://github.com/takanoriyanagitani/rs-pq-inmem-cols2ints"
documentation = "https://docs.rs/rs-pq-inmem-cols2ints/latest"
keywords = ["parquet", "arrow", "wasi", "integer", "convert"]

exclude = [
  "sample.d/input.parquet",
  "sample.d/input.csv",
]

[profile.release-wasi]
inherits = "release"
lto = true
strip = true
opt-level = 's'
codegen-units = 1

[[bin]]
name = "pq-inmem-cols2ints"

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
unwrap_used = "forbid"
expect_used = "forbid"
panic = "forbid"

[dependencies.arrow-array]
version = "59.3.0"
default-features = false
features = [
]

[dependencies.arrow-schema]
version = "59.3.0"
default-features = false
features = [
]

[dependencies.bytes]
version = "1.12.1"
default-features = false
features = [
  "std",
]

[dependencies.parquet]
version = "59.3.0"
default-features = false
features = [
  "arrow",
  "base64",
  "brotli",
  "flate2-rust_backend",
  "lz4",
  "simdutf8",
  "snap",
]
